name: Daily AI Draft

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

env:
  NODE_ENV: production

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Capture date
        id: meta
        run: echo "today=$(date -u +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Generate AI draft
        id: generate
        run: node scripts/generate_post.js
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}
          GEMINI_IMAGE_MODEL: ${{ secrets.GEMINI_IMAGE_MODEL }}
          SITE_URL: https://theloomreport.page

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: add AI draft for ${{ steps.meta.outputs.today }}"
          branch: ai-draft/${{ steps.meta.outputs.today }}
          title: "AI Draft – ${{ steps.meta.outputs.today }}"
          body: |
            Automated AI draft for ${{ steps.meta.outputs.today }}.

            - Generated by `scripts/generate_post.js`
            - Please review moderation results before publishing.
          labels: automation, ai
          add-paths: |
            src/posts/
            src/assets/generated/
          draft: true
